version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8001:8000
    image: app:django
    container_name: django_container
    command: bash -c "python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment :
      MYSQL_HOST : 'localhost'
      MYSQL_DATABASE: 'django_mysql'
      MYSQL_USER : 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
      
    volumes:
      - ./data/mysql/dbb:/var/lib/mysql
    ports:
      - "3306:3306"